; ESPDeka P-3 V1.6 — ESP32-C3 + LR1121 (ex-ExpressLRS Generic C3 LR1121 RX)

[env:espdeka-p3-v16-lr1121]

extends = esp32c3_base

board = esp32-c3-devkitm-1

board_level = extra

board_build.flash_size = 4MB

build_src_filter =
  ${esp32c3_base.build_src_filter}
  +<../variants/esp32c3/espdeka_p3_v16>



custom_meshtastic_architecture = esp32-c3

custom_meshtastic_display_name = ESPDeka P-3 V1.6 LR1121

custom_meshtastic_support_level = 2

custom_meshtastic_tags = ESPDeka,ExpressLRS,LR1121



build_flags =

  ${esp32c3_base.build_flags}

  -D PRIVATE_HW

  -D ESPDEKA_P3_V16

  -D MESHTASTIC_EXCLUDE_I2C=1

  -D MESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1

  -D MESHTASTIC_EXCLUDE_INPUTBROKER=1

  -I variants/esp32c3/espdeka_p3_v16



monitor_speed = 115200

upload_protocol = esptool

upload_speed = 115200


